'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Check, ChevronRight, ChevronLeft, Copy, Zap, Link2, Minus, Plus as PlusIcon } from 'lucide-react'

const PLATFORMS = ['TikTok', 'Instagram', 'Facebook', 'LinkedIn', 'YouTube', 'Pinterest']
const PLATFORM_EMOJI: Record<string, string> = {
  TikTok: '🎵', Instagram: '📸', Facebook: '👥', LinkedIn: '💼', YouTube: '▶️', Pinterest: '📌',
}

const STEPS = [
  { id: 1, title: 'Platform Audit', desc: 'Which platforms are you on?' },
  { id: 2, title: 'Profile Optimisation', desc: 'AI-generated bio suggestions' },
  { id: 3, title: 'Content Setup', desc: 'Posting frequency & content mix' },
  { id: 4, title: 'Auto-Posting', desc: 'Connect your social accounts' },
  { id: 5, title: 'First Week Content', desc: 'Generate 7 days of posts' },
  { id: 6, title: 'Launch', desc: 'Start your marketing mission' },
]

interface PlatformStatus {
  platform: string
  status: 'connected' | 'not_connected' | 'not_on_it'
}

interface ContentFrequency {
  platform: string
  postsPerWeek: number
}

interface ContentMix {
  video: number
  carousel: number
  static: number
}

export default function MarketSetupPage({ params }: { params: Promise<{ locale: string }> }) {
  const router = useRouter()
  const [locale, setLocale] = useState('en')
  const [step, setStep] = useState(1)
  const [platformStatuses, setPlatformStatuses] = useState<PlatformStatus[]>(
    PLATFORMS.map((p) => ({ platform: p, status: 'not_connected' as const }))
  )
  const [bios, setBios] = useState<Record<string, string>>({})
  const [loadingBios, setLoadingBios] = useState(false)
  const [frequencies, setFrequencies] = useState<ContentFrequency[]>(
    PLATFORMS.map((p) => ({ platform: p, postsPerWeek: 3 }))
  )
  const [contentMix, setContentMix] = useState<ContentMix>({ video: 50, carousel: 30, static: 20 })
  const [firstWeekContent, setFirstWeekContent] = useState<Array<{ day: string; platform: string; caption: string; hook: string }>>([])
  const [generatingContent, setGeneratingContent] = useState(false)
  const [launching, setLaunching] = useState(false)
  const [copiedBio, setCopiedBio] = useState<string | null>(null)
  const [businessProfiles, setBusinessProfiles] = useState<Array<{ id: string; business_name: string }>>([])
  const [selectedBPId, setSelectedBPId] = useState('')

  useEffect(() => {
    params.then((p) => setLocale(p.locale))
    fetch('/api/business-profiles').then((r) => r.json()).then((d) => {
      const profiles = d.profiles || d.businessProfiles || []
      setBusinessProfiles(profiles)
      if (profiles[0]) setSelectedBPId(profiles[0].id)
    })
  }, [])

  const activePlatforms = platformStatuses.filter((p) => p.status !== 'not_on_it').map((p) => p.platform)

  async function generateBios() {
    if (!selectedBPId) return
    setLoadingBios(true)
    try {
      const res = await fetch('/api/social/profile-kit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ businessProfileId: selectedBPId, platforms: activePlatforms, locale }),
      })
      const data = await res.json()
      if (res.ok && data.kit) {
        const newBios: Record<string, string> = {}
        for (const platform of activePlatforms) {
          const platformKey = platform.toLowerCase()
          const profileData = data.kit.profiles?.[platformKey] || data.kit.profiles?.[platform]
          if (profileData?.bio) newBios[platform] = profileData.bio
          else newBios[platform] = `${platform} bio for your business — optimised for discoverability and conversions.`
        }
        setBios(newBios)
      }
    } catch {
      const fallback: Record<string, string> = {}
      activePlatforms.forEach((p) => { fallback[p] = `Optimised ${p} bio — edit this with your key services and a call to action.` })
      setBios(fallback)
    } finally {
      setLoadingBios(false)
    }
  }

  async function generateFirstWeek() {
    setGeneratingContent(true)
    try {
      const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
      const content = days.map((day, i) => ({
        day,
        platform: activePlatforms[i % Math.max(1, activePlatforms.length)],
        hook: `Day ${i + 1} hook — compelling opening line to stop the scroll`,
        caption: `This is your ${day} post caption. Add your story, value, and CTA here. Generated by ELEVO Market™.`,
      }))
      setFirstWeekContent(content)
    } finally {
      setGeneratingContent(false)
    }
  }

  async function handleLaunch() {
    if (!selectedBPId) return
    setLaunching(true)
    try {
      const res = await fetch('/api/market/mission', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          businessProfileId: selectedBPId,
          goal: 'Grow presence on ' + activePlatforms.join(', ') + ' with consistent daily content',
          timeframe: '4 weeks',
          budget: 'No paid ads',
          platforms: activePlatforms,
          locale,
          autoExecute: true,
        }),
      })
      if (res.ok) {
        router.push(`/${locale}/market`)
      }
    } finally {
      setLaunching(false)
    }
  }

  function copyBio(platform: string) {
    navigator.clipboard.writeText(bios[platform] || '')
    setCopiedBio(platform)
    setTimeout(() => setCopiedBio(null), 2000)
  }

  function updateFrequency(platform: string, delta: number) {
    setFrequencies((prev) => prev.map((f) =>
      f.platform === platform ? { ...f, postsPerWeek: Math.max(1, Math.min(14, f.postsPerWeek + delta)) } : f
    ))
  }

  return (
    <div className="min-h-screen bg-[#080C14] text-[#EEF2FF] p-6">
      <div className="max-w-2xl mx-auto">
        <div className="mb-8">
          <h1 className="text-2xl font-bold mb-1">Social Setup Wizard</h1>
          <p className="text-sm text-gray-400">Set up your social presence in 6 steps</p>
        </div>

        <div className="flex items-center gap-2 mb-8 overflow-x-auto pb-2">
          {STEPS.map((s, i) => (
            <div key={s.id} className="flex items-center gap-2 shrink-0">
              <button
                onClick={() => step > s.id && setStep(s.id)}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${
                  step === s.id ? 'bg-indigo-600 text-white' :
                  step > s.id ? 'bg-green-500/20 text-green-400 cursor-pointer' :
                  'bg-white/5 text-gray-500'
                }`}
              >
                {step > s.id ? <Check size={10} /> : <span>{s.id}</span>}
                {s.title}
              </button>
              {i < STEPS.length - 1 && <ChevronRight size={14} className="text-gray-600 shrink-0" />}
            </div>
          ))}
        </div>

        <div className="bg-[#141B24] rounded-2xl border border-white/5 p-6">
          {step === 1 && (
            <div className="space-y-4">
              <div className="mb-2">
                <h2 className="text-lg font-semibold">{STEPS[0].title}</h2>
                <p className="text-sm text-gray-400">{STEPS[0].desc}</p>
              </div>
              {businessProfiles.length > 0 && (
                <div className="mb-4">
                  <label className="text-sm text-gray-400 mb-1 block">Business profile</label>
                  <select
                    value={selectedBPId}
                    onChange={(e) => setSelectedBPId(e.target.value)}
                    className="w-full bg-[#1A2332] border border-white/10 rounded-xl px-4 py-2.5 text-sm text-[#EEF2FF]"
                  >
                    {businessProfiles.map((bp) => <option key={bp.id} value={bp.id}>{bp.business_name}</option>)}
                  </select>
                </div>
              )}
              {PLATFORMS.map((p) => {
                const ps = platformStatuses.find((x) => x.platform === p)!
                return (
                  <div key={p} className="flex items-center justify-between p-4 bg-[#1A2332] rounded-xl border border-white/5">
                    <div className="flex items-center gap-3">
                      <span className="text-xl">{PLATFORM_EMOJI[p]}</span>
                      <span className="font-medium">{p}</span>
                    </div>
                    <div className="flex gap-2">
                      {(['connected', 'not_connected', 'not_on_it'] as const).map((s) => (
                        <button
                          key={s}
                          onClick={() => setPlatformStatuses((prev) => prev.map((x) => x.platform === p ? { ...x, status: s } : x))}
                          className={`text-xs px-2.5 py-1 rounded-full border transition-all ${
                            ps.status === s
                              ? s === 'connected' ? 'bg-green-500/20 border-green-500/40 text-green-400'
                                : s === 'not_on_it' ? 'bg-gray-500/20 border-gray-500/40 text-gray-400'
                                : 'bg-indigo-500/20 border-indigo-500/40 text-indigo-400'
                              : 'bg-white/5 border-white/10 text-gray-500'
                          }`}
                        >
                          {s === 'connected' ? 'Connected' : s === 'not_connected' ? 'Not connected' : 'Not on it'}
                        </button>
                      ))}
                    </div>
                  </div>
                )
              })}
            </div>
          )}

          {step === 2 && (
            <div className="space-y-4">
              <div className="mb-2">
                <h2 className="text-lg font-semibold">{STEPS[1].title}</h2>
                <p className="text-sm text-gray-400">{STEPS[1].desc}</p>
              </div>
              {Object.keys(bios).length === 0 ? (
                <div className="text-center py-8">
                  <button
                    onClick={generateBios}
                    disabled={loadingBios}
                    className="bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white px-6 py-3 rounded-xl font-medium transition-colors flex items-center gap-2 mx-auto"
                  >
                    {loadingBios ? (
                      <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...</>
                    ) : (
                      <><Zap size={16} /> Generate AI Bios for {activePlatforms.length} Platforms</>
                    )}
                  </button>
                </div>
              ) : (
                <div className="space-y-3">
                  {activePlatforms.map((p) => (
                    <div key={p} className="bg-[#1A2332] rounded-xl border border-white/5 p-4">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-semibold">{PLATFORM_EMOJI[p]} {p}</span>
                        <button onClick={() => copyBio(p)} className="flex items-center gap-1 text-xs text-gray-400 hover:text-gray-200 transition-colors">
                          {copiedBio === p ? <><Check size={12} className="text-green-400" /> Copied</> : <><Copy size={12} /> Copy</>}
                        </button>
                      </div>
                      <p className="text-sm text-gray-300">{bios[p]}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {step === 3 && (
            <div className="space-y-6">
              <div className="mb-2">
                <h2 className="text-lg font-semibold">{STEPS[2].title}</h2>
                <p className="text-sm text-gray-400">{STEPS[2].desc}</p>
              </div>
              <div>
                <h3 className="text-sm font-medium text-gray-300 mb-3">Posts per week</h3>
                <div className="space-y-3">
                  {activePlatforms.map((p) => {
                    const f = frequencies.find((x) => x.platform === p)!
                    return (
                      <div key={p} className="flex items-center justify-between bg-[#1A2332] rounded-xl p-4 border border-white/5">
                        <span className="text-sm font-medium">{PLATFORM_EMOJI[p]} {p}</span>
                        <div className="flex items-center gap-3">
                          <button onClick={() => updateFrequency(p, -1)} className="w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors">
                            <Minus size={14} />
                          </button>
                          <span className="w-8 text-center font-semibold">{f.postsPerWeek}</span>
                          <button onClick={() => updateFrequency(p, 1)} className="w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors">
                            <PlusIcon size={14} />
                          </button>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
              <div>
                <h3 className="text-sm font-medium text-gray-300 mb-3">Content mix</h3>
                <div className="space-y-3">
                  {(['video', 'carousel', 'static'] as const).map((type) => (
                    <div key={type} className="flex items-center gap-4">
                      <span className="text-sm text-gray-300 w-20 capitalize">{type}</span>
                      <div className="flex-1 h-2 bg-white/5 rounded-full overflow-hidden">
                        <div className="h-full bg-indigo-500 rounded-full transition-all" style={{ width: `${contentMix[type]}%` }} />
                      </div>
                      <span className="text-sm font-medium w-10 text-right">{contentMix[type]}%</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {step === 4 && (
            <div className="space-y-4">
              <div className="mb-2">
                <h2 className="text-lg font-semibold">{STEPS[3].title}</h2>
                <p className="text-sm text-gray-400">{STEPS[3].desc}</p>
              </div>
              {activePlatforms.map((p) => {
                const ps = platformStatuses.find((x) => x.platform === p)!
                return (
                  <div key={p} className="flex items-center justify-between p-4 bg-[#1A2332] rounded-xl border border-white/5">
                    <div className="flex items-center gap-3">
                      <span className="text-xl">{PLATFORM_EMOJI[p]}</span>
                      <div>
                        <p className="font-medium">{p}</p>
                        <p className={`text-xs ${ps.status === 'connected' ? 'text-green-400' : 'text-gray-400'}`}>
                          {ps.status === 'connected' ? 'Connected' : 'Not connected'}
                        </p>
                      </div>
                    </div>
                    {ps.status !== 'connected' && (
                      <a
                        href={`/api/social/oauth/${p.toLowerCase().replace('/', '').replace(' ', '-')}`}
                        className="flex items-center gap-2 bg-indigo-600/20 hover:bg-indigo-600/30 border border-indigo-500/30 text-indigo-300 px-3 py-1.5 rounded-lg text-xs transition-colors"
                      >
                        <Link2 size={12} /> Connect
                      </a>
                    )}
                    {ps.status === 'connected' && (
                      <span className="flex items-center gap-1 text-green-400 text-xs">
                        <Check size={12} /> Connected
                      </span>
                    )}
                  </div>
                )
              })}
              <p className="text-xs text-gray-500 text-center mt-2">You can skip this step and connect later from Social Hub</p>
            </div>
          )}

          {step === 5 && (
            <div className="space-y-4">
              <div className="mb-2">
                <h2 className="text-lg font-semibold">{STEPS[4].title}</h2>
                <p className="text-sm text-gray-400">{STEPS[4].desc}</p>
              </div>
              {firstWeekContent.length === 0 ? (
                <div className="text-center py-8">
                  <button
                    onClick={generateFirstWeek}
                    disabled={generatingContent}
                    className="bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white px-6 py-3 rounded-xl font-medium transition-colors flex items-center gap-2 mx-auto"
                  >
                    {generatingContent ? (
                      <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...</>
                    ) : (
                      <><Zap size={16} /> Generate First Week</>
                    )}
                  </button>
                </div>
              ) : (
                <div className="space-y-3">
                  {firstWeekContent.map((item, i) => (
                    <div key={i} className="bg-[#1A2332] rounded-xl border border-white/5 p-4">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <span className="text-xs font-bold text-gray-400">{item.day}</span>
                          <span className="text-xs text-indigo-400">{item.platform}</span>
                        </div>
                        <div className="flex gap-2">
                          <button className="text-xs text-gray-400 hover:text-gray-200 px-2 py-1 bg-white/5 rounded-lg transition-colors">Approve</button>
                          <button className="text-xs text-gray-400 hover:text-gray-200 px-2 py-1 bg-white/5 rounded-lg transition-colors">Schedule</button>
                        </div>
                      </div>
                      <p className="text-xs text-indigo-300 mb-1 italic">"{item.hook}"</p>
                      <p className="text-sm text-gray-300">{item.caption}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {step === 6 && (
            <div className="space-y-6 text-center">
              <div className="w-16 h-16 bg-indigo-600/20 border border-indigo-500/30 rounded-full flex items-center justify-center mx-auto">
                <Zap size={28} className="text-indigo-400" />
              </div>
              <div>
                <h2 className="text-xl font-bold mb-2">Ready to launch!</h2>
                <p className="text-gray-400 text-sm">Your marketing setup is complete. ELEVO Market™ will build a full 30-day mission and start running your marketing.</p>
              </div>
              <div className="bg-[#1A2332] rounded-xl border border-white/5 p-4 text-left space-y-2">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-400">Platforms</span>
                  <span className="text-[#EEF2FF]">{activePlatforms.join(', ')}</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-400">Total posts/week</span>
                  <span className="text-[#EEF2FF]">{frequencies.filter((f) => activePlatforms.includes(f.platform)).reduce((sum, f) => sum + f.postsPerWeek, 0)}</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-400">Mission length</span>
                  <span className="text-[#EEF2FF]">30 days</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-400">Auto-execute</span>
                  <span className="text-green-400">Enabled</span>
                </div>
              </div>
              <button
                onClick={handleLaunch}
                disabled={launching || !selectedBPId}
                className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-bold py-4 rounded-xl transition-colors flex items-center justify-center gap-2 text-lg"
              >
                {launching ? (
                  <><div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Launching...</>
                ) : (
                  <><Zap size={20} /> Start Marketing Mission (10 credits)</>
                )}
              </button>
            </div>
          )}
        </div>

        <div className="flex justify-between mt-6">
          <button
            onClick={() => setStep((s) => Math.max(1, s - 1))}
            disabled={step === 1}
            className="flex items-center gap-2 text-gray-400 hover:text-gray-200 disabled:opacity-30 transition-colors text-sm"
          >
            <ChevronLeft size={16} /> Back
          </button>
          {step < 6 && (
            <button
              onClick={() => { if (step === 2 && Object.keys(bios).length === 0) generateBios(); setStep((s) => Math.min(6, s + 1)) }}
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2 rounded-xl text-sm font-medium transition-colors"
            >
              {step === 5 ? 'Continue to Launch' : 'Next'} <ChevronRight size={16} />
            </button>
          )}
        </div>
      </div>
    </div>
  )
}
