'use client'

import { Info } from 'lucide-react'

interface ActionExplanationProps {
  contentType: string
  seoScore?: number
  wordCount?: number
}

const contentDescriptions: Record<string, string> = {
  gbp_post: 'This Google Business Profile post is optimised for local search visibility and engagement. Post directly to your GBP to improve your local ranking.',
  blog: 'This blog post is structured for SEO with natural keyword placement. Publish on your website to drive organic traffic.',
  social_caption: 'Crafted for high engagement on social media. Post at peak times (Tue–Thu, 9am–11am or 6pm–8pm) for best reach.',
  review_response: 'A professional response that thanks the customer, mentions your service, and encourages repeat business. Respond within 24 hours of the review for best results.',
  email: 'Email copy designed to drive opens and clicks. A/B test your subject line for best results.',
  seo: 'SEO-optimised copy with natural keyword integration. Implement on your website and submit to Google Search Console.',
  repurposed: 'Content adapted for a new format while preserving your core message and brand voice.',
}

export default function ActionExplanation({ contentType, seoScore, wordCount }: ActionExplanationProps) {
  const description = contentDescriptions[contentType] || 'Content generated by ELEVO AI. Review and personalise before publishing.'

  return (
    <div className="flex gap-3 p-3 bg-accentDim border border-accent/20 rounded-lg">
      <Info size={16} className="text-accent mt-0.5 shrink-0" />
      <div className="space-y-1">
        <p className="text-sm text-dashText">{description}</p>
        <div className="flex gap-4 text-xs text-dashMuted">
          {seoScore !== undefined && (
            <span>SEO Score: <span className={`font-medium ${seoScore >= 80 ? 'text-green-400' : seoScore >= 60 ? 'text-amber-400' : 'text-red-400'}`}>{seoScore}/100</span></span>
          )}
          {wordCount !== undefined && (
            <span>{wordCount} words</span>
          )}
        </div>
      </div>
    </div>
  )
}
