import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx'

interface DocSection {
  heading?: string
  content: string
  level?: 'h1' | 'h2' | 'h3' | 'body'
}

export async function generateDocx(
  title: string,
  sections: DocSection[],
  branding: { businessName: string; language: string }
): Promise<Buffer> {
  const children: Paragraph[] = []

  children.push(new Paragraph({
    children: [new TextRun({ text: title, bold: true, size: 48, font: 'Calibri' })],
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  }))

  children.push(new Paragraph({
    children: [new TextRun({
      text: `Prepared for ${branding.businessName} — Generated by ELEVO AI™`,
      size: 20,
      color: '888888',
      font: 'Calibri',
    })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 600 },
  }))

  for (const section of sections) {
    if (section.heading) {
      const headingLevel = section.level === 'h1' ? HeadingLevel.HEADING_1
        : section.level === 'h3' ? HeadingLevel.HEADING_3
        : HeadingLevel.HEADING_2

      children.push(new Paragraph({
        children: [new TextRun({ text: section.heading, bold: true, size: 28, font: 'Calibri' })],
        heading: headingLevel,
        spacing: { before: 400, after: 200 },
      }))
    }

    const lines = section.content.split('\n').filter(l => l.trim())
    for (const line of lines) {
      children.push(new Paragraph({
        children: [new TextRun({ text: line, size: 22, font: 'Calibri' })],
        spacing: { after: 120 },
      }))
    }
  }

  const doc = new Document({ sections: [{ children }] })
  return Buffer.from(await Packer.toBuffer(doc))
}
